### ISSUE TITLE
Feature: Option to add Cc mails in Apostle

### ISSUE THREAD

**Issue by aswinsanakan** [apostle/apostle-ruby#2]
Missing an option to Cc and Bcc to multiple mails while configuring the mails.

**Comment by snikch** [comment]
Hey there. You can add a cc or bcc directly on a mail object

```rb
mail.cc = "test@example.com"
```

Since there is no concept of a collection of mail objects, there's no single method that can do this, but it's not hard to loop over a collection of objects and call these methods.

```rb
mails.each{|mail| mail.cc = "test@example.com" }
```

**Comment by aswinsanakan** [comment]
Thanks for the quick reply! I found the solution for this after playing around with the gem. I have sent a PR noting this feature in the documentation.
